### ISSUE TITLE
Slack config

### ISSUE THREAD

**Issue by rderewianko** [Webinterpret/hanging-merge-requests#5]
Pardon my ignorance but where do i define my config for slack with api token?

**Comment by matee911** [comment]
Oh, good remark. It's not documented but definitely should be.

Here is the command we use on our internal CI.

```
send-notifications --config-path ../config.json --slack-hook-url $SLACK_HOOK_URL --gitlab-url $GITLAB_URL --gitlab-private-token $GITLAB_PRIVATE_TOKEN --team $TEAM
```

If you have more questions and suggestions for small improvements we can discuss them and perhaps release finally version 1.0 to ease installation via pip.

**Comment by matee911** [comment]
v1.0.0 is available here https://pypi.org/project/hanging-merge-requests/  ;)
